import { LiteralUnion } from 'src/helpers/hoc-types/entityValueTypes'
import { entities, IconsEntity } from 'src/theme/theming/entities'
import { SizeType } from 'src/types/global'

export type IconColors = keyof typeof entities.icons.colors

export type orientation = 'up' | 'down' | 'left' | 'right'

export type SVGProps = {
  size: LiteralUnion<SizeType> | number
  primaryColor: LiteralUnion<IconColors>
  secondaryColor?: LiteralUnion<IconColors>
  onClick?: () => void
  entity: IconsEntity
  orientation?: orientation
}

export type IconType =
  | 'catalog'
  | 'socLogo'
  | 'campaigns'
  | 'gift'
  | 'plus'
  | 'minus'
  | 'tenDoor'
  | 'rightChevron'
  | 'close'
  | 'award'
  | 'contact'
  | 'multipleUsers2x'
  | 'multipleUsers3x'
  | 'information'
  | 'hamburger'
  | 'leftChevron'
  | 'chevron'
  | 'information'
  | 'filterBy'
  | 'groups'
  | 'idCard'
  | 'plusSquare'
  | 'star'
  | 'search'
  | 'cart'
  | 'priceTag'
  | 'layer'
  | 'loading'
  | 'play'
  | 'lock'
  | 'user'
  | 'noUsers'
  | 'add'
  | 'check'
  | 'exclamation'
  | 'envelope'
  | 'userSuccess'
  | 'image'
  | 'imageSwap'
  | 'text'
  | 'color'
  | 'template'
  | 'redo'
  | 'undo'
  | 'copy'
  | 'drag'
  | 'delete'
  | 'crop'
  | 'alignLeft'
  | 'alignRight'
  | 'alignCenter'
  | 'allPanel'
  | 'fullBleed'
  | 'fullBleedLandscape'
  | 'fullBleedPortrait'
  | 'sliderHorizontal'
  | 'sliderVertical'
  | 'cropRotate'
  | 'frame'
  | 'cut'
  | 'wand'
  | 'layerAdd'
  | 'layerRemove'
  | 'layerDisabled'
  | 'signature'
  | 'shadows'
  | 'rotateLeft'
  | 'rotateRight'
  | 'colorPalette'
  | 'dropper'
  | 'textBox'
  | 'fontSize'
  | 'flipHorizontal'
  | 'flipVertical'
  | 'filter'
  | 'brightness'
  | 'aText'
  | 'frameWidth'
  | 'frameHeight'
  | 'layerUp'
  | 'layerDown'
  | 'capitalizedText'
  | 'uppercaseText'
  | 'lowercaseText'
  | 'fullBleedImage'
  | 'fullBleedText'
  | 'panelMode'
  | 'viewPanels'
  | 'rotate'
  | 'view'
  | 'replaceImage'
  | 'quotation'
  | 'facebook'
  | 'instagram'
  | 'twitter'
  | 'linkedIn'
  | 'youtube'
  | 'pinterest'
  | 'visible'
  | 'invisible'
  | 'elementIcon'
  | 'complete'
  | 'download'
  | 'closeCircle'
  | 'backgroundSettings'
  | 'upload'
  | 'stickers'
  | 'clearPanel'
  | 'viewCarousel'
  | 'viewSinglePanel'
  | 'editorText'
  | 'layout'
  | 'background'
  | 'save'
  | 'signaturePen'
  | 'size'
  | 'variable'
  | 'imageUpload'
  | 'squareCheck'
  | 'userTag'
  | 'map'
  | 'mapLocation'
  | 'location'
  | 'creditCard'
  | 'calendar'
  | 'home'
  | 'bag'
  | 'swap'
  | 'warning'
  | 'coaching'
  | 'promptingsIcon'

export type IconProps = {
  name: IconType
} & Omit<SVGProps, 'entity'>
